"""empty message

Revision ID: da3b1c20dee4
Revises: 3ca9ba2bd037
Create Date: 2020-02-25 11:52:43.416166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3b1c20dee4'
down_revision = '3ca9ba2bd037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.create_table('user',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('username', sa.String(length=64), nullable=True),
    # sa.Column('email', sa.String(length=128), nullable=True),
    # sa.Column('password', sa.String(length=128), nullable=True),
    # sa.Column('verified', sa.Boolean(), nullable=True),
    # sa.Column('date created', sa.DateTime(), nullable=True),
    # sa.Column('last query', sa.String(length=512), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.drop_index(op.f('ix_user_username'), table_name='user')
    # op.drop_index(op.f('ix_user_email'), table_name='user')
    # op.drop_table('user')
    # ### end Alembic commands ###
