"""empty message

Revision ID: db80a51c6f21
Revises: da3b1c20dee4
Create Date: 2020-02-25 15:53:52.888555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db80a51c6f21'
down_revision = 'da3b1c20dee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin_approved', sa.Boolean(), default=False))
    op.add_column('user', sa.Column('admin_rights', sa.Boolean(), default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin_rights')
    op.drop_column('user', 'admin_approved')
    # ### end Alembic commands ###
