"""empty message

Revision ID: f6824e1b3581
Revises: 3bddce2a14e6
Create Date: 2020-03-03 11:38:40.164347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6824e1b3581'
down_revision = '3bddce2a14e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'date_created',
             existing_type=sa.DATETIME(),
             nullable=True,
             existing_server_default=sa.text('(CURRENT_TIMESTAMP)')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
