openapi: 3.0.0
info:
  title: Simple API for slips
  version: 0.2.0
servers:
  - url: http://127.0.0.1:5000/api
paths:
  /slips:
    get:
      summary: List all slips
      operationId: flask_app.api.list_slips
      parameters:
        - name: page_id
          in: query
          description: Page number to get. Returns all items if page is 0.
          schema:
            type: integer
            default: 1
            minimum: 0
        - name: per_page
          in: query
          description: Number of items per page.
          schema:
            type: integer
            exclusiveMinimum: true
            minimum: 0
        - name: date
          in: query
          description: One specific date or date range.
          required: true
          schema:
            type: array
            minItems: 1
            maxItems: 2
            items:
              $ref: '#/components/schemas/SlipModel/properties/date'
        - name: object_code
          in: query
          description: Object code.
          required: false
          schema:
            $ref: '#/components/schemas/SlipModel/properties/object_code'
        - name: pos_id
          in: query
          description: POS terminal ID.
          required: false
          schema:
            $ref: '#/components/schemas/SlipModel/properties/pos_id'
      responses:
        200:
          description: Successfully read all slips from db
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        default:
          description: Unexpected error
          content:
            text/plain:
              schema:
                type: string
      security:
        - basic: []
            
    post:
      summary: Add slips
      operationId: flask_app.api.api.add_slips
      requestBody:
        description: Full slip object
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                $ref: '#/components/schemas/SlipModel'
      responses:
        201:
          description: Successfully added slips to db
          content:
            text/plain:
              schema:
                type: string
        default:
          description: Unexpected error
          content:
            text/plain:
              schema:
                type: string
      security:
        - basic: []

  /slips/{date}/{ref_num}:
    parameters:
      - name: date
        in: path
        description: Date of operation
        required: true
        schema:
          $ref: '#/components/schemas/SlipModel/properties/date'
      - name: ref_num
        in: path
        description: Unique operation ID (RRN)
        required: true
        schema:
          $ref: '#/components/schemas/SlipModel/properties/ref_num'
    get:
      summary: Get one slip
      operationId: flask_app.api.get_one_slip
      responses:
        200:
          description: Successfully read a slip from db
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SlipModel'
        default:
          description: Unexpected error
          content:
            text/plain:
              schema:
                type: string
      security:
        - basic: []
    put:
      summary: Update one slip
      operationId: flask_app.api.api.update_one_slip
      requestBody:
        description: Full slip object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SlipModel'
      responses:
        200:
          description: Successfully updated slip
          content:
            text/plain:
              schema:
                type: string
        default:
          description: Unexpected error
          content:
            text/plain:
              schema:
                type: string
      security:
        - basic: []
    delete:
      summary: Delete one slip
      operationId: flask_app.api.api.delete_one_slip
      responses:
        204:
          description: Successfully deleted a slip
          content:
            text/plain:
              schema:
                type: string
        default:
          description: Unexpected error
          content:
            text/plain:
              schema:
                type: string
      security:
        - basic: []
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
      x-basicInfoFunc: flask_app.api.api.basic_auth
  schemas:
    SlipModel:
      type: object
      required:
        - date
        - time
        - operation_type
        - pos_id
        - merchant_num
        - card_number
        - summ
        - ref_num
        - file_link
        - updated
        - object_code
      properties:
        merchant_name:
          type: string
          maxLength: 100
        city:
          type: string
          maxLength: 50
        address:
          type: string
          maxLength: 200
        phone_num:
          type: string
          maxLength: 20
        date:
          type: string
          pattern: '\d{4}-\d{2}-\d{2}'
          maxLength: 10
        time:
          type: string
          pattern: '\d{2}:\d{2}'
          maxLength: 10
        operation_type:
          type: string
          maxLength: 20
        pos_id:
          type: string
          pattern: '\d{4,8}'
          maxLength: 8
        merchant_num:
          type: string
          pattern: '\d{12}'
          maxLength: 12
        fin_service:
          type: string
          maxLength: 50
        something:
          type: string
          maxLength: 50
        card_number:
          type: string
          pattern: '\d{4}'
          maxLength: 4
        card_holder:
          type: string
          maxLength: 100
        summ:
          type: string
        result:
          type: string
          maxLength: 50
        auth_code:
          type: string
          pattern: '[\da-zA-Z]{6}'
          maxLength: 6
        ref_num:
          type: string
          pattern: '\d{12}'
          maxLength: 12
        payment_type:
          type: string
          maxLength: 50
        file_link:
          type: string
          maxLength: 100
        updated:
          $ref: '#/components/schemas/SlipModel/properties/date'
        object_code:
          type: string
          pattern: '([A-Z]\d{3})|([A-Z]{2}\d{2})'
          maxLength: 4
        status:
          type: string
          default: 'Success'
      additionalProperties: false
    DateModel:
      type: object
      properties:
        date:
          $ref: '#/components/schemas/SlipModel/properties/date'
        start_date:
          $ref: '#/components/schemas/SlipModel/properties/date'
        end_date:
          $ref: '#/components/schemas/SlipModel/properties/date'
      additionalProperties: false
      minProperties: 1
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    ResponseModel:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/SlipModel'
        meta:
          $ref: '#/components/schemas/MetaModel'
    MetaModel:
      type: object
      properties:
        page:
          type: integer
        pages:
          type: integer
        items:
          type: integer
        total:
          type: integer
        next:
          type: string
          nullable: true
        prev:
          type: string
          nullable: true
      required:
        - page
        - pages
        - items
        - total
        - next
        - prev